server.port=8002

spring.application.name=dubbo-nacos-consumer
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.registry.port=8848
dubbo.registry.username=nacos
dubbo.registry.password=nacos
dubbo.registry.version=1.0.0
dubbo.protocol.port=-1
# \u6D88\u8D39\u8005\u4E0D\u9700\u8981\u7ED1\u5B9Aip
#dubbo.protocol.host=192.168.1.108
dubbo.registry.preferred=true
# \u7981\u7528QOS\u670D\u52A1
dubbo.application.qos-enable=false

spring.cloud.inetutils.preferred-networks=192.168.1
#spring.cloud.inetutils.ignored-interfaces=
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
